# Generated by Django 6.0.3 on 2026-03-12 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='role',
            new_name='user_type',
        ),
    ]
